spring:
  application:
    name: hospitalManager

  datasource:
    url: jdbc:postgresql://localhost:5432/hospital_manager
    username: postgres
    password: postgres

  jpa:
    show-sql: true

  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 300
    refreshTokenExpiration: 604800


server:
  port: 8081

admin:
  fullName: Christian
  email: isingizwechrisitan@gmail.com
  password: Christian24/07